// Code generated by "stringer -type SchedulerType"; DO NOT EDIT.

package config

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Clock-0]
	_ = x[MultiClock-1]
	_ = x[SimpleTimeEffective-2]
	_ = x[SimpleWithContext-3]
	_ = x[InGoroutine-4]
	_ = x[InGoroutineCancellable-5]
	_ = x[WorkerPool-6]
}

const _SchedulerType_name = "ClockMultiClockSimpleTimeEffectiveSimpleWithContextInGoroutineInGoroutineCancellableWorkerPool"

var _SchedulerType_index = [...]uint8{0, 5, 15, 34, 51, 62, 84, 94}

func (i SchedulerType) String() string {
	if i < 0 || i >= SchedulerType(len(_SchedulerType_index)-1) {
		return "SchedulerType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SchedulerType_name[_SchedulerType_index[i]:_SchedulerType_index[i+1]]
}
