services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - '1777:1777' # pprof extension
      - '8888:8888' # Prometheus metrics exposed by the Collector
      - '8889:8889' # Prometheus exporter metrics
      - '13133:13133' # health_check extension
      - '4317:4317' # OTLP gRPC receiver
      - '4318:4318' # OTLP http receiver
      - '55679:55679' # zpages extension
    networks:
      otel:
        ipv4_address: 192.168.0.3

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    container_name: prometheus
    hostname: prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    environment:
      TZ: "Europe/Moscow"
    networks:
      otel:
        ipv4_address: 192.168.0.2

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'
    networks:
      otel:
        ipv4_address: 192.168.0.6

  stand:
    image: run-go
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./run-go", "-config", "/app/stand/config.yaml"]
    configs:
      - source: stand_config
        target: /app/stand/config.yaml
    networks:
      otel:
        ipv4_address: 192.168.0.5


  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    user: root
    container_name: grafana
    hostname: grafana
    ports:
     - '3000:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      otel:
        ipv4_address: 192.168.0.4

networks:
  otel:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.0.0/16

configs:
  stand_config:
    content: |
      version: v1
      scheduler:
        type: ste
        targets:
          - sleep: 200ms
            interval: 2s
            timeout: 1s
            count: 5000
          - sleep: 200ms
            interval: 4s
            timeout: 1s
            count: 5000
          - sleep: 200ms
            interval: 8s
            timeout: 1s
            count: 5000
          - sleep: 200ms
            interval: 16s
            timeout: 1s
            count: 3000