receivers:
  otlp:
    protocols:
      #grpc:
      #  endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  jaeger:
    protocols:
      thrift_http:
        endpoint: 0.0.0.0:14268
  hostmetrics:
    collection_interval: 2s
    scrapers:
      # CPU utilization metrics
      cpu:
      # Disk I/O metrics
      disk:
      # File System utilization metrics
      filesystem:
      # CPU load metrics
      load:
      # Memory utilization metrics
      memory:
      # Network interface I/O metrics & TCP connection metrics
      network:
      # Paging/Swap space utilization and I/O metrics
      paging:

processors:
  batch:

exporters:
  debug:
  #  verbosity: detailed
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: metrics
  otlp:
    endpoint: 192.168.0.6:4317
    tls:
      insecure: true

extensions:
  pprof:
    endpoint: "0.0.0.0:1777"

service:
  extensions: [pprof]
  pipelines:
    metrics:
      receivers: [otlp, hostmetrics]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp, jaeger]
      processors: [batch]
      exporters: [debug]
