version: v1
scheduler:
  name: clock
  targets:
    - sleep: 500ms
      interval: 2s
      timeout: 1s
      count: 100
    - sleep: 500ms
      interval: 4s
      timeout: 1s
      count: 100
    - sleep: 500ms
      interval: 6s
      timeout: 1s
      count: 100
    - sleep: 500ms
      interval: 8s
      timeout: 1s
      count: 100